
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=UTC&serverTimezone=UTC&useLegacyDate
    username: user
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher